language: ruby
cache: bundler

rvm:
  - 2.2
  - 2.3
  - 2.5
  - 2.6
  - 2.7

gemfile:
  - gemfiles/4.0.gemfile
  - gemfiles/4.1.gemfile
  - gemfiles/4.2.gemfile
  - gemfiles/5.0.gemfile
  - gemfiles/5.1.gemfile
  - gemfiles/5.2.gemfile
  - gemfiles/6.0.gemfile
