language: ruby
cache: bundler

rvm:
- 2.2
- 2.3
- 2.4
- 2.5
- 2.6
- 2.7

gemfile:
- gemfiles/4.0.gemfile
- gemfiles/4.1.gemfile
- gemfiles/4.2.gemfile
- gemfiles/5.0.gemfile
- gemfiles/5.1.gemfile
- gemfiles/5.2.gemfile
- gemfiles/6.0.gemfile
- gemfiles/6.1.gemfile

jobs:
  exclude:
  - rvm: 2.2
    gemfile: gemfiles/6.0.gemfile
  - rvm: 2.2
    gemfile: gemfiles/6.1.gemfile
  - rvm: 2.3
    gemfile: gemfiles/6.0.gemfile
  - rvm: 2.3
    gemfile: gemfiles/6.1.gemfile
  - rvm: 2.4
    gemfile: gemfiles/6.0.gemfile
  - rvm: 2.4
    gemfile: gemfiles/6.1.gemfile
  - rvm: 2.7
    gemfile: gemfiles/4.0.gemfile
  - rvm: 2.7
    gemfile: gemfiles/4.1.gemfile
  - rvm: 2.7
    gemfile: gemfiles/4.2.gemfile
